### ISSUE TITLE
 KeyError: 'CBSwinTransformer is not in the models registry'

### ISSUE THREAD

**Issue by CharlesNJohn** [VDIGPKU/CBNetV2#31]
During handling of the above exception, another exception occurred....
KeyError: "MaskRCNN: 'CBSwinTransformer is not in the models registry'"

I am assuming it has to do something with mmdet/mmcv installation made for CBNetV2? I encountered a similar problem with another model but solved it by installing mmdet for that particular model. I couldn't figure out what's up with this. Any help?

Thank you in anticipation!

**Comment by lgf821793883** [comment]
我也遇到同样的问题

**Comment by RainbowSun11Q2H** [comment]
me too

**Comment by lgf821793883** [comment]
解决了，卸载mmdet 重新pip install  然后在cbnet 下  
运行 python setup.py develop

**Comment by lgf821793883** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VDIGPKU/CBNetV2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VDIGPKU/CBNetV2]  KeyError: 'CBSwinTransformer is not in the models registry' (#31)





  
解决了，卸载mmdet 重新pip install 然后在cbnet 下
 运行 python setup.py develop
  
请问卸载是pip uninstall就行了吗？之前试过一次，好像还是不行
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RainbowSun11Q2H** [comment]
> 解决了，卸载mmdet 重新pip install 然后在cbnet 下
> 运行 python setup.py develop

我在docker里试了确实还是不行

**Comment by RainbowSun11Q2H** [comment]
> 解决了，卸载mmdet 重新pip install 然后在cbnet 下
> 运行 python setup.py develop

哈哈，我知道了，要在cbnet下重新pip install mmdet，这样版本变成2.14.0就行，因为cbnet目录下有个mmdet。如果在其它目录安装mmdet就是2.15的版本。感谢

**Comment by lgf821793883** [comment]
这个问题是环境问题，要不你重新配一下环境&nbsp; 我之前是在 mmdetection下&nbsp; 执行的 pip install mmdet&nbsp;&nbsp; 
现在是在cbnetv2下执行的&nbsp;&nbsp; 并执行 python setup.py develop&nbsp; 



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VDIGPKU/CBNetV2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VDIGPKU/CBNetV2]  KeyError: 'CBSwinTransformer is not in the models registry' (#31)





  
解决了，卸载mmdet 重新pip install 然后在cbnet 下
 运行 python setup.py develop
  
我在docker里试了确实还是不行
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CharlesNJohn** [comment]
Sorry guys, I am having difficulty in translation.

So, what are the steps?
1. `pip uninstall mmdet`
2. `https://github.com/VDIGPKU/CBNet.git` or `https://github.com/VDIGPKU/CBNetV2.git` 
3. `python setup.py develop`

**Comment by CharlesNJohn** [comment]
It worked for me! Thank you guys!!
